name: Deployment workflow
on:
    push:
        branches:
            - master
jobs:
    preparation:
        runs-on: ubuntu-latest
        steps:
            - name: preparation
              run: echo "preparing deploy"

            - name: checks out the repository
              uses: actions/checkout@v4 

            - name: log into docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
            - name: build our code
              env:
                IMAGE_NAME: workflow101
                VERSION: latest
              run: |
                  docker build -t ${IMAGE_NAME}:${VERSION} .